# Generated by Django 5.2.5 on 2025-08-19 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='logout_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='session',
            name='grace_period',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSIS', 'BSIS'), ('BLIS', 'BLIS')], max_length=100),
        ),
    ]
