# Generated by Django 5.2.5 on 2025-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('Custom', 'Custom')], default='Custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
