# Generated by Django 5.2.5 on 2025-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_event_date_event_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flat_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='per_minute_penalty',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
        ),
    ]
