# Generated by Django 5.2.5 on 2025-09-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_event_flat_rate_event_per_minute_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
