# Generated by Django 5.2.5 on 2025-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_session_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rfid',
            field=models.IntegerField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
