# Generated by Django 5.2.5 on 2025-09-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_student_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSIS', 'BSIS'), ('BLIS', 'BLIS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
